import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { FileClock, Search } from 'lucide-react';
import { ApiError, apiFetch } from '../../lib/api';
import { ClientAccessRequestStatus, clientAccessRequestStatusMeta, type AdminAccessRequestItem, type AdminAccessRequestListResponse } from '../../types/auth';
import ClientFormFields from './ClientFormFields';
import { normalizedClient, requestToForm, type ClientFormModel } from './clientFormModel';

const errorText = (error: unknown, fallback: string) => error instanceof ApiError || error instanceof Error ? error.message : fallback;
export default function AccessRequestsPanel() {
  const [items, setItems] = useState<AdminAccessRequestItem[]>([]), [total, setTotal] = useState(0), [page, setPage] = useState(1), [query, setQuery] = useState(''), [status, setStatus] = useState(''), [loading, setLoading] = useState(true), [feedback, setFeedback] = useState('');
  const [selected, setSelected] = useState<AdminAccessRequestItem | null>(null), [mode, setMode] = useState<'approve' | 'reject' | null>(null), [form, setForm] = useState<ClientFormModel | null>(null), [note, setNote] = useState(''), [saving, setSaving] = useState(false);
  const pageSize = 20, pages = useMemo(() => Math.max(1, Math.ceil(total / pageSize)), [total]);
  const load = useCallback(async (nextPage: number) => { setLoading(true); const p = new URLSearchParams({ page: String(nextPage), page_size: String(pageSize) }); if (query.trim()) p.set('q', query.trim()); if (status) p.set('status', status); try { const result = await apiFetch<AdminAccessRequestListResponse>(`/admin/access-requests?${p}`); setItems(result.items); setTotal(result.total); setPage(result.page); } catch (error) { setFeedback(errorText(error, 'Could not load access requests.')); } finally { setLoading(false); } }, [query, status]);
  useEffect(() => { void load(1); }, [load]);
  const reject = async (event: FormEvent) => { event.preventDefault(); if (!selected || !note.trim()) { setFeedback('Enter a rejection reason.'); return; } setSaving(true); try { const updated = await apiFetch<AdminAccessRequestItem>(`/admin/access-requests/${encodeURIComponent(selected.id)}/reject`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ admin_note: note.trim() }) }); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setFeedback('Request rejected. The reason was emailed to the requester.'); setMode(null); } catch (error) { setFeedback(errorText(error, 'Could not reject request.')); } finally { setSaving(false); } };
  const approve = async (event: FormEvent) => { event.preventDefault(); if (!selected || !form) return; let next; try { next = normalizedClient(form); } catch (error) { setFeedback(errorText(error, 'Invalid client.')); return; } setSaving(true); try { const updated = await apiFetch<AdminAccessRequestItem>(`/admin/access-requests/${encodeURIComponent(selected.id)}/approve`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ client_name: next.clientName, client_type: next.clientType, redirect_uris: next.redirectUris, scopes: next.scopes, allowed_audiences: next.allowedAudiences, grant_types: next.grantTypes, token_endpoint_auth_method: next.tokenEndpointAuthMethod, admin_note: note.trim() || null }) }); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setFeedback('Request approved. The requester can now open the one-time credential link from their access-request history.'); setMode(null); } catch (error) { setFeedback(errorText(error, 'Could not approve request.')); } finally { setSaving(false); } };
  return <section className="admin-card glass"><header className="admin-card-head"><h2><FileClock size={18} />Access requests</h2><div className="admin-query-row"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search requests" /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All states</option><option value="pending">pending</option><option value="approved">approved</option><option value="rejected">rejected</option></select><button onClick={() => void load(1)}><Search size={14} />Search</button></div></header>
    {feedback && <p role="status" className="admin-feedback">{feedback}</p>}{loading ? <div className="admin-placeholder">Loading access requests...</div> : <ul className="admin-list">{items.map((item) => { const meta = clientAccessRequestStatusMeta[item.status]; return <li key={item.id} className="admin-list-item"><div><strong>{item.site_name}</strong><p>{item.user_email} · {item.site_url}</p><p>{item.request_description}</p><span className={meta.className}>{meta.label}</span></div>{item.status === ClientAccessRequestStatus.Pending && <div className="admin-list-actions"><button onClick={() => { setSelected(item); setForm(requestToForm(item)); setNote(''); setMode('approve'); }}>Approve</button><button onClick={() => { setSelected(item); setNote(''); setMode('reject'); }}>Reject</button></div>}</li>; })}</ul>}
    <footer className="admin-pagination"><span>Page {page}/{pages} of {total} items</span><button disabled={page <= 1} onClick={() => void load(page - 1)}>Previous</button><button disabled={page >= pages} onClick={() => void load(page + 1)}>Next</button></footer>
    {mode === 'approve' && form && <section role="dialog" aria-modal="true" className="admin-modal"><form onSubmit={approve}><h3>Approve access request</h3><ClientFormFields form={form} onChange={setForm} /><label>Admin note<textarea value={note} onChange={(e) => setNote(e.target.value)} /></label><button type="button" onClick={() => setMode(null)}>Cancel</button><button type="submit" disabled={saving}>Approve request</button></form></section>}
    {mode === 'reject' && <section role="dialog" aria-modal="true" className="admin-modal"><form onSubmit={reject}><h3>Reject access request</h3><label>Rejection reason<textarea aria-label="Rejection reason" value={note} onChange={(e) => setNote(e.target.value)} /></label><button type="button" onClick={() => setMode(null)}>Cancel</button><button type="submit" disabled={saving}>Reject request</button></form></section>}
  </section>;
}
